/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ironCrown.gltf --transform 
Files: ironCrown.gltf [302.37KB] > C:\Users\DELL\obj2gltf\ironCrown-transformed.glb [25.13KB] (92%)
*/
import { Canvas } from "@react-three/fiber";
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
// import { PerspectiveCamera, OrbitControls } from 'drei';
import { Stats, OrbitControls, PerspectiveCamera, Html, Environment, PointerLockControls, RandomizedLight } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/ironCrown-transformed.glb')
  
  if (!nodes) return null;

  return (
    <div>
    <Canvas dpr={[1, 2]} style={{height:"100vh"}}>
      {/* <PerspectiveCamera makeDefault position={[-50, -30, -30]} fov={30} zoom={0.5} /> */}
      {/* <OrbitControls target={[-1.5, 0, 3]} maxDistance={0.1} enableZoom={true} zoomSpeed={10} maxZoom={500} /> */}
      <ambientLight intensity={0.1} castShadow />
      <group {...props} dispose={null}>
        <mesh geometry={nodes.crownbase_low_Mesh003.geometry} material={materials.None} />
      </group>
    </Canvas>
    </div>
  )
}

useGLTF.preload('/ironCrown-transformed.glb')
